version: '3.1'

services:
  sportscenter-mysql:
    image: mysql
    restart: always
    container_name: "sportify-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'your password'
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - sportify-mysql-data:/var/lib/mysql

  sportscenter-redis:
    image: "redis:latest"
    container_name: "sportify-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - sportify-redis-data:/data

volumes:
  sportify-redis-data:
  sportify-mysql-data:
